### ISSUE TITLE
Squash commits in PRs

### ISSUE THREAD

**Issue by apsdehal** [ctfs/write-ups-2015#157]
As we are moving further into the year, no of commits are increasingly significantly in the repo. It is generally a good practice to squash commits from PRs into a single commit and then merge them. This will keep git history/logs clean.

http://programmers.stackexchange.com/questions/263164/why-squash-git-commits-for-pull-requests

**Comment by dhanvi** [comment]
IMHO that's fine not so many so that they can't be handled 

I think the commits are not so big when compared to others like [libre](https://github.com/LibreOffice/core) or Kernel 

also to make sure that we don't mess up with the repos we spitted the write-up with years [ctfs/write-up-2014#292](https://github.com/ctfs/write-ups-2014/issues/292) 

FYI we do have now a 2013 repo too hope we can make good progress in the past too :smile:

**Comment by mathiasbynens** [comment]
I used to do this religiously for `write-ups-2014`: e.g. https://github.com/ctfs/write-ups-2014/commits/master?page=15

When someone submits a 15-line patch that consists of 15 separate commits, please squash them.
